services:
  certs-init:
    image: alpine:3.20
    volumes:
      - ./certs:/certs
    entrypoint: >
      sh -c '
        if [ ! -f /certs/origin.crt ] || [ ! -f /certs/origin.key ]; then
          echo "Generating self-signed TLS cert in /certs...";
          apk add --no-cache openssl;
          mkdir -p /certs;
          openssl req -x509 -nodes -days 365 \
            -newkey rsa:2048 \
            -keyout /certs/origin.key \
            -out /certs/origin.crt \
            -subj "/CN=localhost";
        else
          echo "Certs already exist, skipping generation.";
        fi
      '
    restart: "no"
  data-init:
    image: alpine:3.20
    volumes:
      - .:/app
    entrypoint: >
      sh -c '
        mkdir -p /app/data /app/log;
        chown -R 33:33 /app/data /app/log;
      '
    restart: "no"

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/certs:ro
      - ./nginx/logs:/var/log/nginx
      - .:/app:consistent
    networks:
      - internal-net
    restart: unless-stopped
    depends_on:
      certs-init:
        condition: service_completed_successfully
      web:
        condition: service_started
    ports:
      - "80:80"
      - "443:443"

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_GID: ${DOCKER_GID}
    image: vulschedula-app:latest # Built image
    #privileged: true
    command: >
      sh -c "
        ./wait-for-it.sh redis:6379 --
      "

    ports:
      - "8080:8080"
      - "8000:8000" # in case 8080 is used, use 8000 port
    user: www-data
    depends_on:
      data-init:
        condition: service_completed_successfully
      redis:
        condition: service_started
    restart: on-failure
    env_file:
      - variables.env
    environment:
      - SERVICE_TYPE=web
      - DJANGO_DEV_SERVER=${DJANGO_DEV_SERVER:-True}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app:consistent
    networks:
      - internal-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis In-Memory Data Store
  redis:
    image: redis:7.0-alpine
    restart: always
    env_file:
      - variables.env
    volumes:
      - ./data/redis:/data
    networks:
      - internal-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  internal-net:
    driver: bridge

