# Generated by Django 5.1.7 on 2025-03-30 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioRecording',
        ),
        migrations.RemoveField(
            model_name='interjection',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Interjection',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
