# Generated by Django 5.2 on 2025-04-28 23:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_is_closed_poll_selected_slot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='invited_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_type',
            field=models.CharField(choices=[('public', 'Public (anyone can vote)'), ('private', 'Private (only invited users)'), ('semi', 'Semi-public (authenticated users)')], default='public', max_length=10),
        ),
    ]
